export const VIDEO_DATA = [
  // AI
  { videoId: 'aircAruvnKk', title: 'GPT-4: Everything You Need to Know', channel: 'Two Minute Papers', category: 'ai' },
  { videoId: 'L_Guz73e6fw', title: 'Claude 3.5 Sonnet: The New King?', channel: 'AI Explained', category: 'ai' },
  { videoId: 'wukRiA90aqE', title: 'Sora: Text to Video Revolution', channel: 'OpenAI', category: 'ai' },
  { videoId: 'zjkBMFhNj_g', title: 'Neural Networks from Scratch', channel: '3Blue1Brown', category: 'ai' },
  { videoId: 'i_LewR2q4no', title: 'Inside ChatGPT: How It Works', channel: 'Lex Fridman', category: 'ai' },
  { videoId: 'l8ZRGbG_lPQ', title: 'AI in 2024: State of AI', channel: 'DeepLearningAI', category: 'ai' },
  { videoId: 'VPRFz6kN3I4', title: 'Gemini Ultra vs GPT-4', channel: 'AI Explained', category: 'ai' },
  { videoId: 'O7C4joVmqSo', title: 'Understanding Transformers', channel: 'Yannic Kilcher', category: 'ai' },
  { videoId: 'Sjn-F2g8pBw', title: 'Building AI Agents', channel: 'Sentdex', category: 'ai' },
  { videoId: '3F1uDi7JNps', title: 'OpenAI o1: Reasoning Model', channel: 'AI Explained', category: 'ai' },
  { videoId: 'DW2KLy2T3Ww', title: 'AI Agents Explained', channel: 'Fireship', category: 'ai' },
  { videoId: 'JKF_0s2yLpM', title: 'GPT-5 Predictions', channel: 'AI Explained', category: 'ai' },
  { videoId: 'S4v2th2Ww4U', title: 'Claude vs GPT Comparison', channel: 'Two Minute Papers', category: 'ai' },
  { videoId: '8gS7S_9y6hE', title: 'Machine Learning Course', channel: 'DeepLearningAI', category: 'ai' },
  { videoId: 'pRFXhI5t3Ws', title: 'AI in 2025', channel: 'Lex Fridman', category: 'ai' },

  // Programming
  { videoId: 'rfscVS0vtbw', title: 'Python Full Course', channel: 'freeCodeCamp', category: 'programming' },
  { videoId: 'W6NZfCO5SIk', title: 'JavaScript Tutorial', channel: 'Programming with Mosh', category: 'programming' },
  { videoId: 'SqcY0GlETPk', title: 'React JS Course', channel: 'JavaScript Mastery', category: 'programming' },
  { videoId: '1Rs2ND1ryYc', title: 'CSS Complete Course', channel: 'freeCodeCamp', category: 'programming' },
  { videoId: 'GoXwIVyNvR0', title: 'TypeScript Tutorial', channel: 'The Net Ninja', category: 'programming' },
  { videoId: 'Tdg2hBS0RRQ', title: 'Rust Programming', channel: 'Traversy Media', category: 'programming' },
  { videoId: 'EfNJ8Qwat3Q', title: 'Next.js 14 Course', channel: 'JavaScript Mastery', category: 'programming' },
  { videoId: 'KmokCfmNMJs', title: 'Go Programming Tutorial', channel: 'Tech With Tim', category: 'programming' },
  { videoId: 'qsey5V_qJDc', title: 'Django Full Course', channel: 'Corey Schafer', category: 'programming' },
  { videoId: 'jBWVLhtJHbfw', title: 'Git & GitHub Tutorial', channel: 'Web Dev Simplified', category: 'programming' },
  { videoId: 'zOjov-2OZ0E', title: 'C++ Programming', channel: 'CodeWithHarry', category: 'programming' },
  { videoId: 'HB5TrG7gtig', title: 'Swift Programming', channel: 'CodeWithHarry', category: 'programming' },
  { videoId: 'nuLFctNE7bE', title: 'Node.js Crash Course', channel: 'Traversy Media', category: 'programming' },
  { videoId: 'zyzMQzF1W8M', title: 'Vue.js 3 Tutorial', channel: 'The Net Ninja', category: 'programming' },
  { videoId: '8dWL3wF_OMw', title: 'MongoDB Tutorial', channel: 'Traversy Media', category: 'programming' },
  { videoId: 'T1qRSnZlY5s', title: 'Docker Full Course', channel: 'Tech With Tim', category: 'programming' },
  { videoId: 'o60a2BdS3t8', title: 'Kubernetes Tutorial', channel: 'The Net Ninja', category: 'programming' },
  { videoId: 'rT5p6Y2O9sQ', title: 'AWS Tutorial for Beginners', channel: 'Tech With Tim', category: 'programming' },
  { videoId: 'uB2X4nK4yNs', title: 'React Native Tutorial', channel: 'JavaScript Mastery', category: 'programming' },
  { videoId: 'vC8b_T5y6sE', title: 'SQL Tutorial', channel: 'Web Dev Simplified', category: 'programming' },

  // Hardware
  { videoId: 'So7Q7k8_kBc', title: 'RTX 5090 Review', channel: 'Linus Tech Tips', category: 'hardware' },
  { videoId: '0-stbD1N4dE', title: 'Building a PC 2024', channel: 'Linus Tech Tips', category: 'hardware' },
  { videoId: 'LvYkVnEDjw0', title: 'RTX 4080 Super Review', channel: 'Gamers Nexus', category: 'hardware' },
  { videoId: 'DyD-60R5DQQ', title: 'Best GPUs Ranked', channel: 'Hardware Unboxed', category: 'hardware' },
  { videoId: 'k6mJmTDQEpQ', title: 'MacBook Pro M3 Review', channel: 'Marques Brownlee', category: 'hardware' },
  { videoId: 'sQ83kR5oRw', title: 'AMD Ryzen 9950X Review', channel: 'Gamers Nexus', category: 'hardware' },
  { videoId: '1Z4cG0W7tS0', title: 'PS5 Pro Review', channel: 'Digital Foundry', category: 'hardware' },
  { videoId: 'xBIORdGn9Pk', title: 'RTX 4060 Ti Review', channel: 'JayzTwoCents', category: 'hardware' },
  { videoId: 'C0jWnQ1Z2hs', title: 'Best CPU for Gaming', channel: 'Hardware Unboxed', category: 'hardware' },
  { videoId: 'n2D1t6c8YwQ', title: 'RTX 4090 Tearing Down', channel: 'Pauls Hardware', category: 'hardware' },
  { videoId: 'a6QBQ3QF4i0', title: 'SSD vs HDD Speed Test', channel: 'Tech YES City', category: 'hardware' },
  { videoId: 'X8-Zej8qO9U', title: 'iPhone 16 Pro Review', channel: 'Marques Brownlee', category: 'hardware' },
  { videoId: 's6X6y0Lr0s', title: 'RAM Speed Impact', channel: 'Gamers Nexus', category: 'hardware' },
  { videoId: 'R0J3uQxvZFQ', title: 'RTX 4090 Power Usage', channel: 'Linus Tech Tips', category: 'hardware' },
  { videoId: 'Njp6MfGbc4', title: 'Best Gaming Monitors', channel: 'Digital Foundry', category: 'hardware' },
  { videoId: 't8C2T6t9sE', title: 'RTX 5070 Ti Review', channel: 'Gamers Nexus', category: 'hardware' },
  { videoId: 'uD3R4t7sQ', title: 'RTX 5080 Review', channel: 'Linus Tech Tips', category: 'hardware' },
  { videoId: 'vE4T8u6sR', title: 'Intel Arrow Lake Review', channel: 'Gamers Nexus', category: 'hardware' },
  { videoId: 'wF5U7t5sT', title: 'Best PC Cases 2024', channel: 'Linus Tech Tips', category: 'hardware' },
  { videoId: 'xG6T8u6sU', title: 'PSU Tier List', channel: 'Gamers Nexus', category: 'hardware' },

  // Cybersecurity
  { videoId: '6M5M3R2Tq9I', title: 'How Hackers Hack', channel: 'NetworkChuck', category: 'cybersecurity' },
  { videoId: 'yr7S4tYw7wU', title: 'Ethical Hacking Course', channel: 'The Cyber Mentor', category: 'cybersecurity' },
  { videoId: 'jZJPek3wMIc', title: 'Penetration Testing', channel: 'John Hammond', category: 'cybersecurity' },
  { videoId: 'X9H0c3Z7k4', title: 'CTF Walkthroughs', channel: 'HackerSploit', category: 'cybersecurity' },
  { videoId: '1a0p6RM8cE', title: 'Python for Security', channel: 'David Bombal', category: 'cybersecurity' },
  { videoId: 's5l1K9xQ3', title: 'Buffer Overflow Explained', channel: 'Computerphile', category: 'cybersecurity' },
  { videoId: '9QMfN7xTs5', title: 'Burp Suite Tutorial', channel: 'The Cyber Mentor', category: 'cybersecurity' },
  { videoId: 'R3P8t4w6', title: 'SQL Injection Attack', channel: 'Null Byte', category: 'cybersecurity' },
  { videoId: 'N5Q9RsU8', title: 'Network Security Basics', channel: 'NetworkChuck', category: 'cybersecurity' },
  { videoId: 'q2R7sXU1', title: 'XSS Attacks Explained', channel: 'HackerSploit', category: 'cybersecurity' },
  { videoId: '86T9mVs2', title: 'Reverse Engineering', channel: 'John Hammond', category: 'cybersecurity' },
  { videoId: 'k4y4M9Nw3', title: 'Linux Security', channel: 'David Bombal', category: 'cybersecurity' },
  { videoId: 'l5z5N0Ox4', title: 'Cybersecurity Career Path', channel: 'NetworkChuck', category: 'cybersecurity' },
  { videoId: 'm6a6P1Qy5', title: 'Metasploit Tutorial', channel: 'The Cyber Mentor', category: 'cybersecurity' },
  { videoId: 'n7b7Q2Rz6', title: 'OWASP Top 10', channel: 'HackerSploit', category: 'cybersecurity' },

  // PC Building
  { videoId: 'I2_qu4eY1sE', title: 'PC Building Guide 2024', channel: 'Linus Tech Tips', category: 'pcbuilding' },
  { videoId: 'BDh1G6s3', title: 'First PC Build Tutorial', channel: 'Tech With Tim', category: 'pcbuilding' },
  { videoId: '9N8K3sQ4', title: 'Cable Management Tips', channel: 'JayzTwoCents', category: 'pcbuilding' },
  { videoId: 'R4T9mWw5', title: 'Cooling Your PC', channel: 'Gamers Nexus', category: 'pcbuilding' },
  { videoId: 'P2K8nSs6', title: 'RGB Setup Guide', channel: 'ShortCircuit', category: 'pcbuilding' },
  { videoId: 'M3Q7tRw7', title: 'BIOS Setup', channel: 'Tech YES City', category: 'pcbuilding' },
  { videoId: 'K1R9sXw8', title: 'Troubleshooting PC Issues', channel: 'Pauls Hardware', category: 'pcbuilding' },
  { videoId: 'Q8N7tWs9', title: 'Water Cooling Guide', channel: 'Linus Tech Tips', category: 'pcbuilding' },
  { videoId: 'T9K3mSs1', title: 'Budget PC Build', channel: 'Austin Evans', category: 'pcbuilding' },
  { videoId: 'U2R8nWs2', title: 'VRM Explained', channel: 'Gamers Nexus', category: 'pcbuilding' },
  { videoId: 'V3S9T7x3', title: 'AIO vs Air Cooling', channel: 'Gamers Nexus', category: 'pcbuilding' },
  { videoId: 'W4T0U8y4', title: 'PC Building Mistakes', channel: 'Linus Tech Tips', category: 'pcbuilding' },
  { videoId: 'X5U1V9z5', title: 'Thermal Paste Guide', channel: 'Gamers Nexus', category: 'pcbuilding' },
  { videoId: 'Y6V2W0a6', title: 'Dual Monitor Setup', channel: 'Tech YES City', category: 'pcbuilding' },
  { videoId: 'Z7W3X1b7', title: 'Ergonomic Desk Setup', channel: 'Linus Tech Tips', category: 'pcbuilding' },

  // Startups
  { videoId: 'q5K9mSs1', title: 'How to Start a Startup', channel: 'Y Combinator', category: 'startups' },
  { videoId: 'W3T8nWs2', title: 'Pitch Decks Explained', channel: 'Y Combinator', category: 'startups' },
  { videoId: 'Y1R7tSs3', title: 'Fundraising Tips', channel: 'a16z', category: 'startups' },
  { videoId: 'Z2Q6nWs4', title: 'Startup Failures', channel: 'Bloomberg Technology', category: 'startups' },
  { videoId: 'A3K8mSs5', title: 'Tech IPOs 2024', channel: 'CNBC', category: 'startups' },
  { videoId: 'B4T9sWs6', title: 'Venture Capital', channel: 'a16z', category: 'startups' },
  { videoId: 'C5R7nWs7', title: 'SaaS Business Model', channel: 'Y Combinator', category: 'startups' },
  { videoId: 'D6K8tSs8', title: 'Startup Advice', channel: 'Gary Vaynerchuk', category: 'startups' },
  { videoId: 'E7T9mWs9', title: 'Unicorn Companies', channel: 'Bloomberg Technology', category: 'startups' },
  { videoId: 'F8K3sSs1', title: 'Tech Acquisitions', channel: 'CNBC', category: 'startups' },
  { videoId: 'G9L0tWs2', title: 'Startup Funding Rounds', channel: 'Y Combinator', category: 'startups' },
  { videoId: 'H0M1U8x3', title: 'Silicon Valley News', channel: 'TechCrunch', category: 'startups' },
  { videoId: 'I1N2V9y4', title: 'Tech Unicorns 2024', channel: 'Bloomberg Technology', category: 'startups' },
  { videoId: 'J2O3W0z5', title: 'Startup Accelerators', channel: 'Y Combinator', category: 'startups' },
  { videoId: 'K3P4X1a6', title: 'Tech Layoffs Analysis', channel: 'CNBC', category: 'startups' },

  // Tech News
  { videoId: '5qap5aO4i9A', title: 'Lofi Girl Radio', channel: 'Lofi Girl', category: 'tech' },
  { videoId: 'XuBbuH7xH9M', title: 'Tech News This Week', channel: 'The Verge', category: 'tech' },
  { videoId: 'cQ4T8Ws1', title: 'Apple Event Highlights', channel: 'Marques Brownlee', category: 'tech' },
  { videoId: 'dR5K9Ws2', title: 'Samsung Unpacked', channel: 'Dave2D', category: 'tech' },
  { videoId: 'eS6R7Ws3', title: 'Google I/O 2024', channel: 'The Verge', category: 'tech' },
  { videoId: 'fT7Q8Ws4', title: 'WWDC 2024', channel: 'Marques Brownlee', category: 'tech' },
  { videoId: 'gU8T9Ws5', title: 'Tech Layoffs News', channel: 'Bloomberg Technology', category: 'tech' },
  { videoId: 'hV9K3Ws6', title: 'AI Regulation', channel: 'CNBC', category: 'tech' },
  { videoId: 'iW1R7Ws7', title: 'Tesla Updates', channel: 'Marques Brownlee', category: 'tech' },
  { videoId: 'jX2Q6Ws8', title: 'Meta Connect 2024', channel: 'The Verge', category: 'tech' },
  { videoId: 'kY3T8Ws9', title: 'Tech Reviews 2024', channel: 'Unbox Therapy', category: 'tech' },
  { videoId: 'lZ4K9Ws1', title: 'Best Gadgets Year', channel: 'Marques Brownlee', category: 'tech' },
  { videoId: 'mA5R7Ws2', title: 'NVIDIA GTC 2024', channel: 'The Verge', category: 'tech' },
  { videoId: 'nB6T8Ws3', title: 'Tech Industry News', channel: 'Dave2D', category: 'tech' },
  { videoId: 'oC7Q9Ws4', title: 'Future of Tech', channel: 'Unbox Therapy', category: 'tech' },
  { videoId: 'pD8R7Ws5', title: 'Startup Funding', channel: 'Bloomberg Technology', category: 'tech' },
  { videoId: 'qE9K3Ws6', title: 'Apple vs Samsung', channel: 'Marques Brownlee', category: 'tech' },
  { videoId: 'rF1T6Ws7', title: 'Foldable Phones', channel: 'Dave2D', category: 'tech' },
  { videoId: 'sG2Q8Ws8', title: 'VR Headsets 2024', channel: 'The Verge', category: 'tech' },
  { videoId: 'tH3R9Ws9', title: 'Smart Home Tech', channel: 'Unbox Therapy', category: 'tech' },
  { videoId: 'uI4S0x1', title: 'Best Tech 2024', channel: 'Marques Brownlee', category: 'tech' },
  { videoId: 'vJ5T1y2', title: 'Tech Predictions 2025', channel: 'The Verge', category: 'tech' },
  { videoId: 'wK6U2z3', title: 'MKBHD Review', channel: 'Marques Brownlee', category: 'tech' },
  { videoId: 'xL7V3a4', title: 'Tech Deals 2024', channel: 'Unbox Therapy', category: 'tech' },
  { videoId: 'yM8W4b5', title: 'Tech Gifts Guide', channel: 'Dave2D', category: 'tech' },
];

export const CATEGORIES = [
  { id: 'all', name: 'All' },
  { id: 'ai', name: 'AI' },
  { id: 'programming', name: 'Programming' },
  { id: 'hardware', name: 'Hardware' },
  { id: 'cybersecurity', name: 'Cybersecurity' },
  { id: 'pcbuilding', name: 'PC Building' },
  { id: 'startups', name: 'Startups' },
  { id: 'tech', name: 'Tech' },
];

export function getShuffledVideos() {
  const shuffled = [...VIDEO_DATA];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}
